<?php
$lang[0] = "🇷🇺 Русский";
$lang[1] = "🇬🇧 English";		 

//RUSSIAN
$text[0][0] = "AirDrop NFT";
$text[0][1] = "Повысить шанс";
$text[0][2] = "Позвать друзей";
$text[0][3] = "Добро пожаловать в AirDrop NFT котов @TonNFTcat из удивительного мира мультивселенной и легендарных собак @TonNFTdog из цифрового сопротивления от Tegro!&#13;&#10;&#13;&#10;Победитель получит: @TonSherlock Crypto Sherlock&#13;&#10;&#13;&#10;До конца месяца разыграем 35 NFT, а количество победителей может быть до 25 человек.&#13;&#10;&#13;&#10;Дополнительно мы раздадим 100 TON. Монеты будут распределены между самыми активными партнёрами.&#13;&#10;&#13;&#10;🆓 Один участник AirDrop может выиграть от 1 до 3 NFT в AirDrop. И 100 случайных пользователей получат по 1 TON в @TegroMoneybot";
$text[0][4] = "Выберите язык:";
$text[0][5] = "Продолжить";
$text[0][6] = "Изменить";
$text[0][7] = "Ваш кошелёк сохранен, если это он: &#13;&#10;&#13;&#10;%walletno%&#13;&#10;&#13;&#10;- нажмите Продолжить, если не Ваш - нажмите Изменить";
$text[0][8] = "Приглашайте активных пользователей в бот и получайте 0.1% шанса за каждого активного приглашенного.&#13;&#10;&#13;&#10;Вы пригласили: &#13;&#10;Активных: %numOfReferals% человек.&#13;&#10;Неактивных: %nonActiveReferals% человек.&#13;&#10;&#13;&#10;Используйте эту ссылку для приглашения пользователей:&#13;&#10;https://t.me/LuckNFTbot?start=%chat_id%";
$text[0][9] = "Участвовать";
$text[0][10] = "Примите участие в розыгрыше NFT коллекций, который пройдёт 30 апреля в 22:00";
$text[0][11] = "Вы можете повысить свой шанс получения NFT от 10%, и так до 50%&#13;&#10;&#13;&#10;За 1 приглашенного друга, вы получаете +0.1% к шансу на победу, но можете повысить свой шанс на выигрыш в AirDrop и платно. 1 TON = 1% к шансу на выигрыш NFT от Tegro.&#13;&#10;&#13;&#10;Повысить шанс можно максимум до 50% на 1 кошелёк и 1 аккаунт Telegram&#13;&#10;&#13;&#10;Для повышения шанса введите свой кошелёк TON:";
$text[0][12] = "Для повышения шанса примите участие в конкурсе";
$text[0][13] = "Я подписался, проверьте";
$text[0][14] = "Для участия в розыгрыше NFT коллекций тебе нужно выполнить следующие условия:";
$text[0][15] = " зарегистрировался по вашей партнерской ссылке.&#13;&#10;&#9;&#9;&#9;&#9;&#9;&#13;&#10;Используйте эту ссылку для приглашения пользователей:&#13;&#10;https://t.me/LuckNFTbot?start=%ref%";
$text[0][16] = "Cпасибо что участвуешь. &#13;&#10;Твой ID участника - %chat_id%&#13;&#10;Шанс выиграть NFT - %points%%&#13;&#10;&#13;&#10;Чтобы повысить шанс на победу Нажми - «Повысить шанс»";
$text[0][17] = "Oops! Вы не подписаны на 3 канала. Пожалуйста подпишитесь!";
$text[0][18] = "В TON Wallet";
$text[0][19] = "Я перевел, проверьте!";
$text[0][20] = "Чтобы повысить шанс выиграша до 51% переведите от 1 Toncoin до 50 Toncoin с указанного кошелька, для повышения шанса выигрыша. На кошелек:&#13;&#10;&#13;&#10;%recepientWallet%&#13;&#10;&#13;&#10;Ссылка для перехода к оплате:&#13;&#10;ton://transfer/%recepientWallet%";
$text[0][21] = "Введите свой кошелёк TON:";
$text[0][22] = "Спасибо. Ваш платёж получен.&#13;&#10;Шанс увеличен на %pointsnow%%";
$text[0][23] = "ОШИБКА! Ваш платеж не обнаружен. Попробуйте повторить проверку несколько позже.";
$text[0][24] = "ОШИБКА! Введенное значение не похоже на кошелек. Введите корректный кошелек:";
$text[0][25] = "ОШИБКА! Кашелек не валиден. Введите корректный кошелек:";
$text[0][26] = " Подписаться на Twitter";
$text[0][27] = "Подписка TGR Telegram";
$text[0][28] = "Подписка Tegro Telegram";
$text[0][29] = "Подписаться в VK";
$text[0][30] = "Добавить токен в MetaMask";
$text[0][31] = "Отправить номер кошелька";
$text[0][32] = "Дарим 50,000&#13;&#10;Первый массовый Crypto Airdrop от разработчиков из команды Tegro!&#13;&#10;&#13;&#10;Благодаря тебе, нас уже более 30,000 человек во всем мире. По этому поводу мы дарим монеты на общую сумму в пятьдесят тысяч долларов в TGR! Каждый участник получит 2 TGR. Выполни несколько простых шагов и получи гарантированную награду!&#13;&#10;&#13;&#10;🗓 Начало: 27 апреля 12:00, окончание: 1 сентября 11:59 МСК&#13;&#10;&#13;&#10;Что нужно сделать:&#13;&#10;&#13;&#10;1️⃣ Подписаться на TGR в Twitter https://twitter.com/tgrtoken&#13;&#10;2️⃣ Подписаться на TGR в Telegram https://t.me/TgrTON&#13;&#10;3️⃣ Подписаться на Tegro в Telegram @Tegro_Money&#13;&#10;4️⃣ Подписаться на TGR в VK https://vk.com/tgrton &#13;&#10;5️⃣ Добавить токен в MetaMask https://tegro.money/vittominacori&#13;&#10;6️⃣ Отправить номер кошелька в сети BSC или TON&#13;&#10;&#13;&#10;";
$text[0][33] = "Мы отправим 2 TGR на ваш кошелек в сеть Binance Smart Chain или в сеть The Open Network.";
$text[0][34] = "Спасибо за участие";
$text[0][35] = "❌ ОШИБКА! Введенное значение не похоже на кошелек. Введите корректный кошелек:";
$text[0][36] = "Спасибо, ваши данные сохранены.&#13;&#10;&#13;&#10;После завершения AirDrop, или раньше, если вами выполнены все условия, на ваш кошелек поступит 2 TGR.";
$text[0][37] = "❌ ОШИБКА! Кoшелек невалиден. Введите корректный кошелек:";
$text[0][38] = "Ваш кошелёк сохранен, если это он: &#13;&#10;&#13;&#10;%walletno%&#13;&#10;&#13;&#10;- нажмите Продолжить, если не Ваш - нажмите Изменить";
$text[0][39] = "Продолжить";
$text[0][40] = "Изменить";
$text[0][41] = "Отправьте либо номер своего кошелька Toncoin в сети The Open Network для получения 2 TGR TON или отправьте номер кошелька в сети Binance Smart Chain для получения 2 TGR BSC на свой кошелек:";
$text[0][42] = "Пригласи друга прямо отсюда и получи бонус!";
$text[0][43] = "🎁 Пригласить друзей";
$text[0][44] = "Отправить приглашение";
$text[0][45] = "🥳 Привет, мне тоже захотелось присоединиться к этому тренду и подарить тебе скидку на покупку NFT";
$text[0][46] = "🎁 Получить скидку на NFT";
$text[0][47] = "Some extra text";


//ENGLISH
$text[1][0] = "AirDrop NFT";
$text[1][1] = "Increase Chance";
$text[1][2] = "Invite friends";
$text[1][3] = "Welcome to AirDrop NFT cats from the amazing world of the multiverse and legendary dogs from Tegro&#39;s digital resistance!&#13;&#10;&#13;&#10;In our bot, we will give away 150 NFTs every month, and the number of winners can be 100 people.&#13;&#10;&#13;&#10;Additionally, we will give away 100 Toncoin. Coins will be distributed among the most active partners.&#13;&#10;&#13;&#10;🆓 One AirDrop participant can win from 1 to 3 NFTs in AirDrop. And 100 random users will receive 1 TON in @TegroMoneybot";
$text[1][4] = "Select a language:";
$text[1][5] = "Continue";
$text[1][6] = "Edit";
$text[1][7] = "Your wallet has been saved if this is:&#13;&#10;&#13;&#10;%walletno%&#13;&#10;&#13;&#10;- click Continue, if not yours - click Change";
$text[1][8] = "Invite active users to the bot and get a 0.1% chance for each active invitee.&#13;&#10;&#13;&#10;You invited:&#13;&#10;Active: %numOfReferals% people.&#13;&#10;Inactive: %nonActiveReferals% people.&#13;&#10;&#13;&#10;Use this link to invite users:&#13;&#10;https://t.me/LuckNFTbot?start=%chat_id%";
$text[1][9] = "Participate";
$text[1][10] = "Take part in the drawing of NFT collections, which will be held on April 30 at 22:00";
$text[1][11] = "You can increase your chance of getting NFT from 10% up to 50%&#13;&#10;&#13;&#10;For 1 invited friend, you get +0.1% to the chance to win, but you can increase your chance to win in AirDrop and for a fee. 1 TON = 1% chance to win NFT from Tegro.&#13;&#10;&#13;&#10;You can increase the chance to a maximum of 50% for 1 wallet and 1 Telegram account&#13;&#10;&#13;&#10;To increase the chance, enter your TON wallet:";
$text[1][12] = "Enter the contest to increase your chance";
$text[1][13] = "I subscribed, please check";
$text[1][14] = "To participate in the NFT Collection Giveaway, you must meet the following conditions:";
$text[1][15] = " Signed up using your affiliate link.&#13;&#10;&#13;&#10;Use this link to invite users:&#13;&#10;https://t.me/LuckNFTbot?start=%ref%";
$text[1][16] = "Thank you for participating.&#13;&#10;Your member ID is %chat_id%&#13;&#10;Chance to win NFT - %points%%&#13;&#10;&#13;&#10;To increase the chance of winning, press - &#34;Increase the chance&#34;";
$text[1][17] = "Oops! You are not subscribed to Channel 3. Please subscribe!";
$text[1][18] = "To TON Wallet";
$text[1][19] = "I have translated, please check!";
$text[1][20] = "In order to increase the chance of winning up to 51%, transfer from 1 Toncoin to 50 Toncoin from the specified wallet to increase the chance of winning. To the wallet:&#13;&#10;&#13;&#10;%recepientWallet%&#13;&#10;&#13;&#10;Link to proceed to payment:&#13;&#10;ton://transfer/%recipientWallet%";
$text[1][21] = "Enter your wallet TON:";
$text[1][22] = "Thank you. Your payment has been received.&#13;&#10;Chance increased by %pointsnow%%";
$text[1][23] = "ERROR! Your payment was not found. Please try again later.";
$text[1][24] = "ERROR! The value you entered does not match the wallet. Please enter a valid wallet:";
$text[1][25] = "ERROR! Wallet is not valid. Please enter a valid wallet:";
$text[1][26] = "Follow on Twitter";
$text[1][27] = "Follow TGR Telegram";
$text[1][28] = "Follow Tegro Telegram";
$text[1][29] = "Follow TGR on VK";
$text[1][30] = "Add token to MetaMask";
$text[1][31] = "Send wallet number";
$text[1][32] = "Giving $50,000🎁&#13;&#10;The first massive Crypto Airdrop from the developers from the Tegro team!&#13;&#10;&#13;&#10;Thanks to you, we are already over 30,000 people all over the world. On this occasion, we are giving away coins for a total of fifty thousand dollars in TGR! Each participant will receive 2 TGR. Follow a few simple steps and get a guaranteed reward!&#13;&#10;&#13;&#10;🗓 Start: April 27 12:00 AM, End: September 1 11:59 AM PDT&#13;&#10;&#13;&#10;What should be done:";
$text[1][33] = "We will send 2 TGR to your wallet on Binance Smart Chain or The Open Network.";
$text[1][34] = "Thanks for participating";
$text[1][35] = "❌ ERROR! The value you entered does not match the wallet. Please enter a valid wallet:";
$text[1][36] = "Thank you, your details have been saved.&#13;&#10;&#13;&#10;After the AirDrop is completed, or earlier if you meet all the conditions, 2 TGR will be credited to your wallet.";
$text[1][37] = "❌ ERROR! Wallet is invalid. Please enter a valid wallet:";
$text[1][38] = "Your wallet has been saved if this is: &#13;&#10;&#13;&#10;%walletno%&#13;&#10;&#13;&#10;- click Continue, if not yours - click Edit";
$text[1][39] = "Continue";
$text[1][40] = "Edit";
$text[1][41] = "Send either your Toncoin wallet number on The Open Network to receive 2 TGR TON or send your wallet number on Binance Smart Chain to receive 2 TGR BSC to your wallet:";
$text[1][42] = "Refer a friend from here and get a bonus!";
$text[1][43] = "🎁 Invite Friends";
$text[1][44] = "Send Invite";
$text[1][45] = "🥳 Hi, I also wanted to join this trend and give you a discount for buying NFTs";
$text[1][46] = "🎁 Get NFT Discount";
$text[1][47] = "Some extra text";
?>